install.packages("rmarkdown", dep = TRUE)
install.packages("tinytex")
tinytex::install_tinytex()  # install TinyTeX
1+1
install.packages("rmarkdown")
install.packages("quantmod")
library(quantmod)
getSymbols("WMT", src = "yahoo", from = "2010-01-01", to = "2019-12-31")
View(WMT)
nrow(WMT)
ncol(WMT)
p <- WMT$WMT.Close
plot.ts(p)
(acf(p))
Box.test(p, lag=10, type='Ljung')
rd <- diff(log(p))
rd_reg <- rd[!is.na(rd)]
View(rd)
View(rd_reg)
plot.ts(rd_reg)
(acf(rd_reg))
head(rd_reg)
View(rd_reg)
mean(rd_reg)
sd(rd_reg)
median(red_reg)
median(rd_reg)
rw <- apply.weekly(rd, FUN = sum)
rm <- apply.monthly(rd, FUN = sum)
nrow(rw)
nrow(rm)
rw_reg <- rw[!is.na(rw)]
rm_reg <- rm[!is.na(rm)]
(acf(rw_reg))
(acf(rm_reg))
par(mfrow = c(3, 1))
plot.ts(rd_reg, main="Log Daily Returns")
plot.ts(rw_reg, main="Log Weekly Returns")
plot.ts(rm_reg, main="Log Monthly Returns")
par(mfrow = c(1, 1))
Box.test(rd_reg, lag=10, type="Ljung-Box")
Box.test(rw_reg, lag=10, type="Ljung-Box")
Box.test(rm_reg, lag=10, type="Ljung-Box")
plot.ts(rd_reg, main="Log Daily Returns")
plot.ts(rw_reg, main="Log Weekly Returns")
plot.ts(rm_reg, main="Log Monthly Returns")
mean(rw_reg)
mean(rm_reg)
